[package]
name = "ece1724-rust-study"
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
publish = false

[dependencies]

[[bin]]
name = "lec3_variables"
path = "src/lectures/lec3/variables_and_mutability.rs"

[[bin]]
name = "lec3_constants_static"
path = "src/lectures/lec3/constants_and_static.rs"

[[bin]]
name = "lec3_scope_shadowing"
path = "src/lectures/lec3/scope_and_shadowing.rs"

[[bin]]
name = "lec3_input_parsing"
path = "src/lectures/lec3/input_parsing.rs"

[[bin]]
name = "lec3_type_inference"
path = "src/lectures/lec3/type_inference.rs"

[[bin]]
name = "lec3_integer_types"
path = "src/lectures/lec3/integer_types.rs"

[[bin]]
name = "lec3_numeric_operations"
path = "src/lectures/lec3/numeric_operations.rs"

[[bin]]
name = "lec3_type_conversions"
path = "src/lectures/lec3/type_conversions.rs"

[[bin]]
name = "lec3_booleans"
path = "src/lectures/lec3/booleans.rs"

[[bin]]
name = "lec3_characters"
path = "src/lectures/lec3/characters.rs"
